### ISSUE TITLE
double weg, nur noch BigDecimal

### ISSUE THREAD

**Issue by MichaeIDietrich** [MichaeIDietrich/Numerik-Project#1]
wie der Titel schon sagt, wollen wir am liebsten überall (wo es denn geht) auf double verzichten und dafür BigDecimal nehmen aus bekannten Gründen der Rechenungenauigkeit ;)

**Comment by MichaeIDietrich** [comment]
ich habe jetzt erstmal in der Matrix-Klasse überall double zu BigDecimal geändert

**Comment by falcopr** [comment]
Ich denke, dieses Issue bezieht sich auf Vektoren und Matrizen. Dort wurde dieses bereits refactored.
