### ISSUE TITLE
Abfangen von Mehrdeutigkeit und Nullenmultiplikation bei der Dreieckmatrixerstellung

### ISSUE THREAD

**Issue by falcopr** [MichaeIDietrich/Numerik-Project#13]
Beispielsweise bei der LU-Zerteilung wird eine Dreiecksmatrix erstellt. Es sollen Tests eingebaut werden, die Fälle abdecken, wenn eine Matrix mehrdeutig ist bzw. eine Dreiecksmatrix bereits Nullen in den Zellen hat.

**Comment by 76Filou** [comment]
Ich verstehe die Aufgabe nicht. Bitte präziser. Eine LU-Zerlegung einer Matrix besitzt zwei Dreiecksmatrizen, eine Obere und eine Untere. Wann genau soll eine Matrix mehrdeutig sein bzw. was bedeutet Mehrdeutigkeit in Bezug auf Matrizen?

**Comment by falcopr** [comment]
Eine Matrix mit A mit einem Vector b kann ein Gleichungssystem darstellen Ax = b.
Wenn die Matrix nicht regulär ist (Rang ist nict nxn/ es existiert keine Inverse/die Dominante der Matrix A ist 0), dann kommt es zu mehrdeutigen lösungen für x.

**Comment by 76Filou** [comment]
Und weiter? Ich verstehe immer noch nicht...

**Comment by falcopr** [comment]
Was macht der Algorithmus dann? Einen Fehler werfen, wenn man kein ordentliches x herausbekommt? Dieser Fall sollte aufjedenfall abgedeckt werden, dass heißt, man sollte hierbei die Matrix überprüfen, ob diese regulär ist. / was verstehst du daran nicht?
Notfalls kannst du auch den bug umschreiben / schließen und präziser stellen. Ich hatte hier nur eine Art brainstorming gemacht.

**Comment by 76Filou** [comment]
Ach so, du meinst, wenn der Rang der Matrix kleiner als die Dimension der Matrix und der Lösungsraum unendlich ist? Hmm, mehrdeutig war hier ein wenig... mehrdeutig. Wie dem auch sei. Kripfgans gibt uns eine reguläre Matrix. Wenn nicht, gibt es eine Division durch Null bei der LU-Zerlegung. Dann wissen wir, dass es keine keine solche Matrix ist und brauchen uns weder über eine LU-Zerlegung, noch über eine Inverse, noch über eine Eigenwertberechnung Gedanken machen. Ich denke dieser Fall ist fakultativ.

**Comment by falcopr** [comment]
Ich meine, dieser Fall ist nicht optional ist. Denn wenn man soeinen Fehler abfangen kann, dann weiß man entweder, dass am Algorthmus was nicht stimmt, man falsch eingetippt hat oder die Aufgabe war tatsächlich so gestellt, um unser Grundwissen zu testen, was ich definitiv nicht ausschließe.
Stell dir außerdem mal vor, es kommt wirklich zu dieser "Division durch 0"-Exception, hast du in der Klausur die Zeit das zu debuggen?

**Comment by MichaeIDietrich** [comment]
Naja, wenn wir dann den Expression-Modus nutzen, dann ist eigtl. geplant, dass auf Exceptions angemessen reagiert, heißt einfach nur, dass ich mit einem try-catch  die die Methode zurückverfolgen kann, die den Fehler prodiziert und kann somit auch diesen Ausgeben. Eine Division durch 0 in der LU-Zerlegungs-Methode lässt sich wahrscheinlich einzig und allein auf darauf zurückführen, dass der Rang der Matrix eben kleiner als die Dimension ist.

**Comment by falcopr** [comment]
Da fällt mir außerdem ein, dass wir mal besprechen sollten, wie wir das Exception-Handling machen sollen, denn das ist für mich noch nicht ersichtlich.

Außerdem ging es mir hierbei nur um gute lesbarkeit des Programmes/ wenn man eine Fehlerursache weiß, dann kann man sie auch in einer Exception ausschreiben und zwar bereits während der Implementierung einer Funktion. Was ist besser und verbraucht weniger Zeit beim verständnis, wenn ihr folgenden Fehler seht: 1. Eine Zahl lässt sich nicht durch 0 teilen, oder 2. Vorsicht!!! Die Matrix xyz ist nicht regulär und hat daher mehrdeutige Lösungen.

Wann willst du überhaupt das try-catch einbauen / wann sollen den die Exceptions eingebaut werden?  wenn mans ganz zum schluss gemacht werden soll, dann werden fehlerfälle sicherlich vergessen!

**Comment by MichaeIDietrich** [comment]
Gut, dass du das ansprichst Falco, habe gerade deswegen eine Issue angelegt. Siehe Issue #21.
