### ISSUE TITLE
Tests für Grundrechenarten der Matrizen

### ISSUE THREAD

**Issue by falcopr** [MichaeIDietrich/Numerik-Project#15]
Bitte für die Skalarmultiplikation, Addition, Subtraktion und Multiplikation von Matrizen tests schreiben!

**Comment by ille90** [comment]
Addition läuft, weitere Grundrechenarten werden geprüft

**Comment by ille90** [comment]
Multiplikation läuft auch, werde das Ganze noch mit doubles testen

**Comment by falcopr** [comment]
Wenn du mit doubles, Gleitkommazahlen meinst, reich es auch, wenn du im Konstruktor der BigDecimal-Zahl einen String übergibst, wie dieser hier "0.00011E+x" E --> ist der Exponent 10^x, der Exponent ist Optional

**Comment by falcopr** [comment]
Addition wurde fehlerhaft geprüft, denn es wurde das Runden nicht geprüft!!! Bitte notfalls bereinigen!

**Comment by falcopr** [comment]
Bitte mal beenden, Illos!

**Comment by ille90** [comment]
Runden der Addition ist nicht notwendig, da sich die Präzision der Eingabewerte durch die Rechenoperation nicht auf das Ergebnis auswirken. Mit anderen Worten: wenn man beliebige Zahlen mit x Stellen anch dem Komma addiert, haben sie danach dieselbe Präzision.
Falls ich da dennoch etwas übersehe bei den Tests, dann erläutere es bitte gegebenenfalls an einem Beispiel.

Habe Schwierigkeiten mit dem Multiplikation. Dort klappt das Runden tatsächlich nicht. Fehler wie folgt:

> > ```
> >          org.junit.ComparisonFailure: expected:<0.30632[9]> but was:<0.30632[87]>              <<
> > ```

Der String enthält dabei den Wert "0.306329", die Präzision liegt bei 6 und Runden ist eingeschaltet. 
Bei einer Präzision von 5 zum Vergleich:

> > ```
> >          org.junit.ComparisonFailure: expected:<0.30632[9]> but was:<0.30632[4]>              <<.
> > ```

**Comment by ille90** [comment]
Subtraktion hinzugefügt, sollte nix mehr offen sein bitte den Issue schließen

**Comment by falcopr** [comment]
Interessant wäre es eigentlich mal gewesen, wenn du beispielsweise eine ganz große Zahl von einer ganz Kleinen abziehst oder eine ganz große zahl mit einer kleinen zahl multiplizierst, etc., um zu sehen, ob die Grundrechenarten wirklich richtig runden.

**Comment by falcopr** [comment]
Revision: 33cc846142255484a4059b86ab0e89d5ae1fcf01
Author: falcoprescher
Date: 25.06.2012 13:35:59
Message:
#15 Tests für Grundrechenarten der Matrizen

Hinzufügen der gewünschten Extremfälle

## Außerdem hinzufügen des Rundens für jeden Input einer Zahl

Modified : Numerik Project/src/numerik/calc/Matrix.java
Modified : Numerik Project/src/numerik/tests/Matrix_TestFixture.java
