### ISSUE TITLE
JavaDoc Kommentare zu allen Funktionen

### ISSUE THREAD

**Issue by falcopr** [MichaeIDietrich/Numerik-Project#24]
Es sollte zu jeder Funktion die JavaDocs Kommentare hinzugefügt werden, damit man beim Benutzen der Intellisense funktion in Eclipse sich etwas zu den Funktionen belesen kann.

Wie siehts damit aus?

**Comment by MichaeIDietrich** [comment]
JavaDoc ist keine schlechte Sache, aber ich bin ziemlich schreibfaul, weiß nicht, wer Lust hat diese Docs anzulegen, also ich würde die Priorität auf niedrig setzen und es erstmal nur auf komplexere Funktionen beschränken, soll heißen, das ich das bei den Grundrechenarten für unnötig halte.
