### ISSUE TITLE
Status quo des Projektes schriftlich angeben und stetig aktualisieren

### ISSUE THREAD

**Issue by falcopr** [MichaeIDietrich/Numerik-Project#26]
Es sollte schriftlich festgehalten werden, in wie weit das Projekt fertig ist im hinblick auf die Übungen.

Bsp.: Übung 3, sind die und die Funktionen, wie viel Prozent dort schon fertig implementiert wurde/ ob da noch was zu machen ist/ etc. 

so sollte es dann aussehen
Übung 1: 2% (die und das fehlt, aber das und das ist implementiert)
Übung 2: 100% (die und das fehlt, aber das und das ist implementiert)
Übung 3: 23% (die und das fehlt, aber das und das ist implementiert)
Übung 4: 24% (die und das fehlt, aber das und das ist implementiert)
Übung 5: 99% (die und das fehlt, aber das und das ist implementiert)
Übung 6: 50% (die und das fehlt, aber das und das ist implementiert)

100% ist es dann nur wirklich, wenn man dann im nachhinein nichts mehr an dem teil verändert, der zu der jeweiligen Übung korrespondiert.

**Comment by falcopr** [comment]
Der Grund dafür ist, dass man dann nicht ewig lang suchen muss, um zu wissen, was fehlt. Es hilft dann, mehr selbstständig zu arbeiten und wichtig ist dann, dass die Issues angelegt werden, damit keine Duplikate vorkommen.

**Comment by MichaeIDietrich** [comment]
Japp, da stimme ich zu, dass wir da mal eine Art Übersicht für brauchen. Carsten weiß da wohl am ehesten über den Fortschritt Bescheid.

**Comment by falcopr** [comment]
Wollte nur noch mal dran erinnern, was Carschtos nun noch gefunden hat, was eingebaut werden muss.

Kontraktionsintervall berechnen
Auswerten und Berechnen von Fehlerhaften Eingaben

Bitte bei weiteren Erweiterungen ergänzen + Issues anlegen (wichtig) und denen zuteilen, die daran arbeiten.

**Comment by falcopr** [comment]
Alles ist implementiert, außer das Kontraktionsintervall!
