### ISSUE TITLE
Einweisung in den grafischen/ Latex Teil des Numerik-Projects + weiteres Voranschreiten?

### ISSUE THREAD

**Issue by falcopr** [MichaeIDietrich/Numerik-Project#27]
Ich würde gerne mal anfragen, wann ihr mal Zeit habt, damit wir uns mal dinge in dem Projekt anschauen, die für den einen oder anderen unklar sind.
Außerdem wäre es gut, wenn jemand auch soeine art schulung gibt, um mit dem umgang der Anwendung klar zu kommen.

Desweiten muss auch klargestellt werden, wie wir das in die GUI einbauen werden, da das mir bisher sehr unklar ist.
Teile der Implementierung ist in der numerik.task und Teile sind in dem numerik.calc Package. Für das "durcheinander" würde ich dann auch ne kurze erklärung haben wollen

**Comment by MichaeIDietrich** [comment]
Also ein Task ist eine Aufgabe, Beispiel: LU-Zerlegung, Binär-zu-Dezimal-Umrechnung, etc, hingegen ist calculation dafür gedacht, Klassen und Methoden bereitzustellen, die von den einzelnen Tasks verwendet werden können.

Tasks greifen nicht aufeinander zu, das heißt, sie sind unabhängig von einander, jeder Task stellt ein Tab am unterem Teil der Anwendung dar.

Zur Latex-Sache ist es am einfachsten sich bereits bestehen Quellcode bzw. Carsten oder mich mündlich zu fragen, da es wohl zu viel Aufwand wäre, jede Funktion schriftlich zu erläutern, weil wenn man sich 1 ... 2 ... 3 Funktionen angeschaut hat, versteht man eigtl auch die Funktionsweise der meisten anderen Funktionen.

**Comment by falcopr** [comment]
Schriftlich den Quellcode für die Latex-Sache wollte ich das nicht unbedingt, es hätte auch gereicht, wenn wir das mal mündlich besprechen, zumindest den werdegang, wie mans am besten in eine funktion implementiert und wie und wo es ausgegeben werden soll und kann.

**Comment by MichaeIDietrich** [comment]
ja, das können wir dann gleich mal machen, wenn du willst

**Comment by 76Filou** [comment]
Wie weit seid ihr mit der Einführung vorangekommen? Ist noch Klärungsbedarf? Kann ich helfen?

**Comment by falcopr** [comment]
Ist alles im Lot! Einführung war erfolgreich.
