### ISSUE TITLE
Probleme bei der Benutzung von Trigonometrische Funktionen

### ISSUE THREAD

**Issue by falcopr** [MichaeIDietrich/Numerik-Project#30]
Da die Math-Bibliothek von Java nur mit double bei den trigonometrischen funktionen umgehen kann, müssen wir uns erstmal im klaren werden, wie wir bei gleichungen mit solchen funktionen vorgehen werden. 

Zu untersuchen sind rundungsfehler, konvertierungsfehler von double zu bigdecimal.
etc.
- was euch noch dazu einfällt.

**Comment by 76Filou** [comment]
Ich habe alle Funktionen für die Newton-Iteration mit der Genauigkeit double eingebunden. Die Genauigkeit ist hier Maschinengenauigkeit und damit für die Klausur ausreichend (~> sinngemäß Kripfganz). BigDecimal lassen wir an diesen Stellen weg.

**Comment by falcopr** [comment]
Kann dann wohl geschlossen werden, wenn doubles benutzt werden.
