### ISSUE TITLE
Jakobiiteration kann nur mit 4x4 matrizen umgehen

### ISSUE THREAD

**Issue by falcopr** [MichaeIDietrich/Numerik-Project#31]
Es soll geprüft werden, ob man mit dem verfahren auch 3x3 matrizen mit einem 3x1 vektor iterieren kann.

**Comment by 76Filou** [comment]
Die LU-Zerlegung funktioniert auch nicht mehr bei bestimmten Matrizen. Es scheint also kein Problem der Jakobi-Iteration zu sein. Da müssen wir ein wenig tiefer graben...

**Comment by 76Filou** [comment]
Ich habe den Fehler gefunden. Es liegt am Auslesen der Datei data.txt. Sobald man neuen Matrizen den gleichen Anfangsbuchstaben gibt, wie einer bereits existierenden Matrix, werden diese an die schon Existierende angehangen. Kommt bereits A in data.txt vor, werden alle anderen Matrizen A1, Ab, AA usw. die nach A folgen an A angehangen. Damit ist die Matrix A natürlich nicht mehr quadratisch.

Aus einer Matrix A 3x3 und einer Matrix A1 3x3 wird die Matrix A 6x3.

**Comment by falcopr** [comment]
Revision: 227a382142973995aca0b135ab0912d8cbd84f90
Author: falcoprescher
Date: 10.06.2012 21:07:56
Message:
#31 Jakobiiteration kann nur mit 4x4 matrizen umgehen bug

## Das Problem wurde verursacht durch die statische Länge des StartVektorX0, die immer 4 Zellen lang war.

Modified : Numerik Project/src/numerik/tasks/JacobiIteration.java
