### ISSUE TITLE
Erzeugen eines NewVectorControls

### ISSUE THREAD

**Issue by falcopr** [MichaeIDietrich/Numerik-Project#32]
So, wie es das NewMatrixControl gibt, sollte auch eins fürs Vektor existieren.

**Comment by MichaeIDietrich** [comment]
Ist gebaut als eigene Klasse, ist fast vollständig eine Kopie von NewMatrixWindow, aber das ist ja auch egal, wollte mir einfach nur die Mühe sparen

**Comment by falcopr** [comment]
Ist damit wohl erledigt.
