### ISSUE TITLE
Rundungsfunktion für doubles + Rechenungenauigkeit von doubles

### ISSUE THREAD

**Issue by falcopr** [MichaeIDietrich/Numerik-Project#34]
Wie man beispielsweise im Tab von Runge Kutta 4 sehen kann, wird in der Tabelle für eine Schrittgröße h = 0.2 folgendes iterriert --> xi = 0, 0.2, 0.4, 0.600000000000001.

Außerdem fehlt uns eine Rundungsfunktion für doubles?
Wie habt ihr das gemacht --> Umwandlung in ein BigDecimal und dann die BigDecimal-Rundung genutzt?
Beim Newton-Verfahren ist es beispiel auch nicht drin mit dem Runden.

Es ist wichtig zu wissen, wo Rundung notwendig ist und wo nicht.

**Comment by MichaeIDietrich** [comment]
meiner Meinung nach sollte immer gerundet werden, damit ich ich nach jeder Operation, sei es Multiplikation, Division, Addition oder Subtraktion, es könnte sich die Mantissenlänge bei jeder dieser Operationen ändern, deswegen sollte es auch nach jeder gemacht werden ... meiner Meinung nach

Wie es aber jetzt mit double aussieht weiß ich auch nicht, wird double in vielen Tasks verwendet? Könnte man vllt. die Stellen, wo es verwendet wirtd nicht doch durch BigDecimal (oder der neuen Klasse Decimal) ersetzen?
