### ISSUE TITLE
MathLib.RoundingMethod "EXACT" into "BINARY"

### ISSUE THREAD

**Issue by ille90** [MichaeIDietrich/Numerik-Project#35]
Bitte den Wert entsprechend Titel ändern. EXACT berechnet die Mantisse zur Berechnung binär. Das ist aus dem Wert nicht ersichtlich. Dementsprechend auch über die Änderung des analogen Wertes NORMAL in DEZIMAL überdenken.

Noch ein Vorschlag ist, den Wert anschließend standardmäßig von BINARY auf DEZIMAL zu stellen, da wir standardmäßig in Aufgaben dezimale Mantissen berechnen.

Gruß vom ille

**Comment by falcopr** [comment]
Bei solchen Sachen bitte nicht einfach "Schließen".

Am besten immer ne kleine erklärung abgeben, denn wenn man schon seine Zeit dafür investiert hat, dann will man auch sehen, was rauskam.

EXACT heißt auf Mantissenlänge runden und
NORMAL heißt auf bestimmte Nachkommastellen runden.
