### ISSUE TITLE
SolveNonLinearEquation mit manueller Ableitung

### ISSUE THREAD

**Issue by falcopr** [MichaeIDietrich/Numerik-Project#38]
Wäre es möglich, dass man das eintragen der ableitungen wieder manuell eintragen kann bei dem tab solve nonlinear equation? 

Im moment wurde das ja gelöscht und durch eine iterative funktion ersetzt.
Ich bin da nämlich etwas misstrauisch in hinblick auf mögliche fehler.

**Comment by falcopr** [comment]
Ich meine das natürlich nicht im selben tab, sondern in ein extratab, beispielsweise.

**Comment by 76Filou** [comment]
Besteht die Skepsis gegenüber der  Richtigkeit der 1. und 2. Ableitung in NonLinEquSolve immer noch oder können wir der/die/das Issue schließen?

**Comment by falcopr** [comment]
Ich denke, dass wir das mit guten gewissen schließen können.
Wir haben ja herausgefunden, dass das bis auf die 6-7 Stelle (Mantissenlänge) genau ist.
Der Fehler ist ja unter 1% und beim iterieren müsste das dann sowieso irgenwann mal konvergieren.
