### ISSUE TITLE
Einbauen des Logarithmuses mit hoher Präzision

### ISSUE THREAD

**Issue by falcopr** [MichaeIDietrich/Numerik-Project#4]
Es soll eine Logarithmusfunktion gebaut werden, bei der man die Präzision des Ergebnisses festlegen kann.

**Comment by MichaeIDietrich** [comment]
ich habe jetzt erstmal eine Logarithmus Funktion eingefügt von http://www.humbug.in/stackoverflow/de/logarithm-of-a-bigdecimal-739532.html, dort gibt es dafür mehrere Versuche zur Umsetzung
die Funktion ist aber noch nicht getestet und nicht final

**Comment by MichaeIDietrich** [comment]
siehe Issue #10

**Comment by falcopr** [comment]
Bei solchen Funktionen verwenden wir nur noch doubles
