### ISSUE TITLE
Implementation der Grundrechenarten für Matrizen

### ISSUE THREAD

**Issue by falcopr** [MichaeIDietrich/Numerik-Project#5]
Es sollen mindestens folgende Funktionen für Matrizen implementiert werden:

Addition,
Multiplikation,
Skalarmultiplikation.

Subtraktion ergibt sich aus der Addition, kann aber als Extramethode implementiert werden.

Bei Division weiß ich nicht so recht, ob das so einfach möglich ist. (War das nicht das Multiplizieren mit einer inversen Matrix?)

**Comment by MichaeIDietrich** [comment]
Wie sieht es mit Subtraktion und Division aus? Das fehlt noch, oder soll das nicht rein?

**Comment by falcopr** [comment]
Ich bin mir nicht sicher, ob wir Division brauchen, aber ich denke nicht.
Subtraktion wäre ein Nice To Have und zur lesbarkeit bestimmt gut geeignet, zumal die Implementation ein Einzeiler ist -->    return this.add(matrixToSubtract.scalarMultiply(-1)); oder so

**Comment by falcopr** [comment]
Alles, was benötigt wird, ist implementiert!
