### ISSUE TITLE
Testen des toString bei Matrizen und Vektoren

### ISSUE THREAD

**Issue by falcopr** [MichaeIDietrich/Numerik-Project#53]
siehe Name

**Comment by ille90** [comment]
läuft gut, habe auch mal Einsicht in die Funktion genommen - soweit ich das sehe gibt es bei der Ausgabe keine Probleme

**Comment by ille90** [comment]
hab nun zuletzt noch einen separaten String angelegt und die Kommentare gelöscht, guck's dir an
