### ISSUE TITLE
MathLib.round-Funktion

### ISSUE THREAD

**Issue by MichaeIDietrich** [MichaeIDietrich/Numerik-Project#6]
hierfür sollten hinreichend Testfälle angelegt
ich habe die Funktion erstmal von Carstens Projekt weitesgehend übernommen
es gibt noch ungenutzt Variablen und auskommentierten Code, deswegen denke ich, dass die Funktion noch nicht alle Fälle der Rundung abdeckt

**Comment by falcopr** [comment]
Revision: abdc040f301c228b0fa1f9189230a2e88140875a
Author: falcoprescher
Date: 27.04.2012 23:27:40
Message:
Resolved some Conflicts while Adding Round-Function

---

Modified : Numerik Project/src/numerik/calc/MathLib.java

Revision: d099c06c27a68fd6e94dd8d65fbab3c10bce309d
Author: falcoprescher
Date: 27.04.2012 23:24:15
Message:
Merge branch 'master' of https://github.com/FrecherxDachs/Numerik-Project

Conflicts:

##     Numerik Project/src/numerik/calc/MathLib.java

Added : Numerik Project/Matrix1.txt
Modified : Numerik Project/src/numerik/Main.java
Modified : Numerik Project/src/numerik/calc/MathLib.java
Modified : Numerik Project/src/numerik/calc/Matrix.java
Added : Numerik Project/src/numerik/calc/Vector.java
Modified : Numerik Project/src/numerik/calc_test/MathLib_TestFixture.java
Modified : Numerik Project/src/numerik/ui/LatexFormula.java
Modified : Numerik Project/src/numerik/ui/OutputFrame.java
Modified : Numerik Project/src/numerik/calc/BigDecimalExtension.java
Modified : Numerik Project/src/numerik/calc/MathLib.java
Modified : Numerik Project/src/numerik/calc_test/MathLib_TestFixture.java
