### ISSUE TITLE
Implementierung von einer Methode "Normalisierung"

### ISSUE THREAD

**Issue by falcopr** [MichaeIDietrich/Numerik-Project#7]
Es soll möglich sein, dass man eine Matrix normalisieren kann.

**Comment by 76Filou** [comment]
Bitte näher beschreiben was darunter zu verstehen ist.

**Comment by falcopr** [comment]
Hmm... Ich frage mich, warum das hier geschlossen wurde.

Mit einer Normalisierung der Matrix meine ich laut Übung 2 Aufgabe 2 das umformen der Matrix, dass in jeder Zeile die Zeilensumme = 1 ist.
Bei Vektoren könnte man das auch machen. Dort war es etwas anders, das die x-y-z Koordinaten des Vektors die Länge 1 ergeben.

**Comment by falcopr** [comment]
Ich hab es mal an mich zugewiesen und baue das nur erstmal in die mathlib ein

**Comment by 76Filou** [comment]
Das "Normalisieren" einer Matrix gibt es schon. Das brauchen wir nicht mehr zu implementieren. In der Klasse Matrix zu finden unter "getScaleOf()". Der Name wurde deshalb gewählt, weil Normalisieren irreführend ist, es ist kein Orthonormalisierungsverfahren wie bei Vektoren und damit auch nicht zu vergleichen. Es ist in erster Linie ein numerisches Optimierungsverfahren.

Ich würde auch gerne das Label der Checkbox "normalisieren" in der LU-Zerlegung in "optimieren" umbenennen.

**Comment by falcopr** [comment]
das kannst du machen. das zeigt wieder, würde sowas in nem issue stehen, dann wüsste mans bereits :).

für vektoren gibt es aber keine normalisierungsmethode. ich denke die müsste mit rein, da sie sehr elementar ist.

**Comment by 76Filou** [comment]
Gut, ich benenne das Label um.
