### ISSUE TITLE
Integration von LaTeX-Funktionen zur nutzerfreundlichen Nutzung

### ISSUE THREAD

**Issue by MichaeIDietrich** [MichaeIDietrich/Numerik-Project#9]
damit ist eben gemeint LaTeX komplett zu kapseln in einer eigenen Klasse, so dass man eigtl. keine Ahnung von LaTeX haben muss, um Formeln auszugeben

**Comment by MichaeIDietrich** [comment]
"nutzerfreundlich" :p

**Comment by falcopr** [comment]
In wie weit ist das jetzt schon integriert? Bitte mal Meldung geben oder Issue schließen.

**Comment by falcopr** [comment]
bei weiteren Issues sollte das spezifiziert werden.
